# Generated by Django 3.2.5 on 2021-08-08 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_mainannouncements'),
        ('staff_user', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uploadfile', models.FileField(upload_to='Notes', verbose_name='Upload File')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.department')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user.Notes.sem+', to='staff_user.subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user.Notes.subject+', to='staff_user.subject')),
            ],
        ),
    ]
