# Generated by Django 3.2.5 on 2021-08-08 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0003_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='sem',
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_user.subject'),
        ),
    ]
