# Generated by Django 3.2.5 on 2021-08-08 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_mainannouncements'),
        ('staff_user', '0005_rename_subject_notes_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='sem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff_user.subject', verbose_name='sem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='staff_user.subject', verbose_name='Subject'),
        ),
    ]
