# Generated by Django 3.2.5 on 2021-08-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0007_auto_20210808_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100, verbose_name='semester'),
        ),
    ]
