# Generated by Django 3.2.4 on 2021-06-19 02:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_department_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('Description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='Activity_uploads', verbose_name='Activity images')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
