# Generated by Django 3.2.4 on 2021-06-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='image',
            new_name='activity_image',
        ),
    ]
