# Generated by Django 3.2.4 on 2021-06-21 05:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_rename_image_activity_activity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Facility name')),
                ('Description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('facilities_image', models.ImageField(upload_to='', verbose_name='Facility image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_image',
            field=models.ImageField(blank=True, upload_to='Activity_uploads', verbose_name='Activity images'),
        ),
    ]
