# Generated by Django 3.2.4 on 2021-06-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_auto_20210621_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilities',
            old_name='facilities_image',
            new_name='image',
        ),
    ]
