# Generated by Django 3.2.4 on 2021-07-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='T_image',
            field=models.ImageField(upload_to='Teachers_photo', verbose_name='Teacher image'),
        ),
    ]
