# Generated by Django 3.2.4 on 2021-07-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_alter_teachers_t_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Eamil Address'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='T_image',
            field=models.ImageField(blank=True, null=True, upload_to='Teachers_photo', verbose_name='Image'),
        ),
    ]
