# Generated by Django 3.2.4 on 2021-07-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_auto_20210715_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
