# Generated by Django 3.2.4 on 2021-07-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_alter_teachers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teachers Name'),
        ),
    ]
